all:

run:
	python3 verifier.py

solve:
	python3 solver.py fl_25_2 
	python3 solver.py fl_50_6 
	python3 solver.py fl_100_1 
	python3 solver.py fl_100_7 
	python3 solver.py fl_200_7 
	python3 solver.py fl_500_7 
	python3 solver.py fl_1000_2 
	python3 solver.py fl_2000_2

test: 
	python3 verifier.py fl_25_2 1
	python3 verifier.py fl_50_6 1
	python3 verifier.py fl_100_1 1
	python3 verifier.py fl_100_7 1
	python3 verifier.py fl_200_7 1
	python3 verifier.py fl_500_7 1
	python3 verifier.py fl_1000_2 1
	python3 verifier.py fl_2000_2 1
