all:

run:
	python verifier.py

test:
	python3 solver.py ks_30_0
	python3 solver.py ks_30_0_wc
	python3 solver.py ks_50_0
	python3 solver.py ks_50_0_wc
	python3 solver.py ks_200_0
	python3 solver.py ks_200_0_wc
	python3 solver.py ks_400_0
	python3 solver.py ks_400_0_wc
	python3 solver.py ks_1000_0
	python3 solver.py ks_1000_0_wc
	python3 solver.py ks_10000_0
	python3 solver.py ks_10000_0_wc
