all:

run:
	python verifier.py

solve:
	python3 solver.py ks_30_0
	python3 solver.py ks_30_0_wc
	python3 solver.py ks_50_0
	python3 solver.py ks_50_0_wc
	python3 solver.py ks_200_0
	python3 solver.py ks_200_0_wc
	python3 solver.py ks_400_0
	python3 solver.py ks_400_0_wc
	python3 solver.py ks_1000_0
	python3 solver.py ks_1000_0_wc
	python3 solver.py ks_10000_0
	python3 solver.py ks_10000_0_wc

test:	
	python3 verifier.py ks_30_0 2
	python3 verifier.py ks_30_0_wc 2
	python3 verifier.py ks_50_0 2
	python3 verifier.py ks_50_0_wc 2
	python3 verifier.py ks_200_0 2
	python3 verifier.py ks_200_0_wc 2
	python3 verifier.py ks_400_0 2
	python3 verifier.py ks_400_0_wc 2
	python3 verifier.py ks_1000_0 2
	python3 verifier.py ks_1000_0_wc 2
	python3 verifier.py ks_10000_0 2
	python3 verifier.py ks_10000_0_wc 2
