all:

run:
	python3 verifier.py

solve:
	python3 solver.py gc_50_3 
	python3 solver.py gc_70_7 
	python3 solver.py gc_100_5
	python3 solver.py gc_250_9
	python3 solver.py gc_500_1
	python3 solver.py gc_1000_5

test: 
	python3 verifier.py gc_50_3 1
	python3 verifier.py gc_70_7 1
	python3 verifier.py gc_100_5 1
	python3 verifier.py gc_250_9 1
	python3 verifier.py gc_500_1 1
	python3 verifier.py gc_1000_5 1
